export interface Stock {
    Id: number;
    Name: string;
    Code: string;
    StockSubSectorId: number;
    SubSectorName: string;
    StockSectorId: number;
    SectorName: string;
    NewSubIndustryId: number;
    NewSubIndustryName: string;
    NewIndustryId: number;
    NewIndustryName: string;
    NewSubSectorId: number;
    NewSubSectorName: string;
    NewSectorId: number;
    NewSectorName: string;
    Last: number;
    PrevClosingPrice: number;
    AdjustedClosingPrice: number;
    AdjustedOpenPrice: number;
    AdjustedHighPrice: number;
    AdjustedLowPrice: number;
    Volume: number;
    Frequency: number;
    Value: number;
    OneDay: number;
    OneWeek: number;
    OneMonth: number;
    ThreeMonth: number;
    SixMonth: number;
    OneYear: number;
    ThreeYear: number;
    FiveYear: number;
    TenYear: number;
    Mtd: number;
    Ytd: number;
    Per: number;
    Pbr: number;
    Capitalization: number;
    BetaOneYear: number;
    StdevOneYear: number;
    PerAnnualized: number;
    PsrAnnualized: number;
    PcfrAnnualized: number;
    AdjustedAnnualHighPrice: number;
    AdjustedAnnualLowPrice: number;
    LastDate: string;
    LastUpdate: string;
    Roe: number;
}

export const defaultStock: Stock = {
    Id: 0,
    Name: "",
    Code: "",
    StockSubSectorId: 0,
    SubSectorName: "",
    StockSectorId: 0,
    SectorName: "",
    NewSubIndustryId: 0,
    NewSubIndustryName: "",
    NewIndustryId: 0,
    NewIndustryName: "",
    NewSubSectorId: 0,
    NewSubSectorName: "",
    NewSectorId: 0,
    NewSectorName: "",
    Last: 0,
    PrevClosingPrice: 0,
    AdjustedClosingPrice: 0,
    AdjustedOpenPrice: 0,
    AdjustedHighPrice: 0,
    AdjustedLowPrice: 0,
    Volume: 0,
    Frequency: 0,
    Value: 0,
    OneDay: 0,
    OneWeek: 0,
    OneMonth: 0,
    ThreeMonth: 0,
    SixMonth: 0,
    OneYear: 0,
    ThreeYear: 0,
    FiveYear: 0,
    TenYear: 0,
    Mtd: 0,
    Ytd: 0,
    Per: 0,
    Pbr: 0,
    Capitalization: 0,
    BetaOneYear: 0,
    StdevOneYear: 0,
    PerAnnualized: 0,
    PsrAnnualized: 0,
    PcfrAnnualized: 0,
    AdjustedAnnualHighPrice: 0,
    AdjustedAnnualLowPrice: 0,
    LastDate: "",
    LastUpdate: "",
    Roe: 0,
  };

  
  